# Generated by Django 5.1 on 2024-11-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='fecha_instalacion',
            field=models.DateField(),
        ),
    ]
